#!/bin/bash

FORCE_REBUILD=0

print_help() {
	printf "Usage: $0 [options]\n"
	printf "Options:\n"
	printf "  --force-rebuild            Force rebuild of the pianoberry-build image.\n"
	printf "  --help                     Show this help message.\n"
}

while [ $# -gt 0 ]; do
	case "$1" in
		--force-rebuild)
			FORCE_REBUILD=1
			;;
		--help)
			print_help
			exit 0
			;;
		*)
			printf "***************************\n"
			printf "* Error: Invalid argument.*\n"
			printf "***************************\n\n"
			print_help
			exit 1
	esac
	shift
done

if [ "$FORCE_REBUILD" -eq 1 ] || [ -z "$(docker image ls | grep pianoberry-build)" ]; then
  echo "Building pianoberry-build image"
  OLD_IMAGE_ID=$(docker images | grep 'pianoberry-build' | awk '{print $3}' | head -n 1)
  if [ -n "$OLD_IMAGE_ID" ]; then
    docker rmi "$OLD_IMAGE_ID"
  fi
  docker build --no-cache -q -t pianoberry-build .
fi

mkdir -p deploy

docker run --privileged --rm -it -v ./deploy:/build pianoberry-build:latest
