#!/bin/sh

URL="http://repo.tinycorelinux.net"
TINYCORE_SERIES="16.x"
TINYCORE_RELEASE="16.0.0"
TINYCORE_ARCH="aarch64"
TINYCORE_IMAGE="piCore64-${TINYCORE_RELEASE}"

PACKAGES="
	alsa.tcz
	bzip2-lib.tcz
	expat2.tcz
	freetype.tcz
	glib2.tcz
	graphite2.tcz
	harfbuzz.tcz
	libasound.tcz
	libdrm.tcz
	libGLES.tcz
	liblzma.tcz
	libpng.tcz
	libX11.tcz
	libXau.tcz
	libXaw.tcz
	libxcb.tcz
	libXdmcp.tcz
	libXext.tcz
	libXfixes.tcz
	libxshmfence.tcz
	libxml2.tcz
	libXxf86vm.tcz
	libzstd.tcz
	llvm19-lib.tcz
	mesa.tcz
	pcre2.tcz
	fontconfig.tcz
"

echo "Building with:"
echo "  serial: ${PIANOTEQ_SERIAL}"
echo "  initial preset: ${PIANOTEQ_INITIAL_PRESET}"

mkdir -p /build/src
cd /build/src

download_file() {
	if [ ! -f "${1##*/}" ]; then
		echo "Downloading ${1}"
		wget ${1}
		if [ $? -ne 0 ]; then
			echo "Failed to download ${1}"
			rm -f ${1##*/}

			if [ "$2" -eq 1 ]; then
				return 1
			else
				exit 1
			fi
		fi
	else
		echo "${1##*/} already exists, skipping download"
	fi
}

download_tcz() {
	download_file ${URL}/${TINYCORE_SERIES}/${TINYCORE_ARCH}/tcz/${1}.tree 1

	if [ $? -ne 0 ]; then
		download_file ${URL}/${TINYCORE_SERIES}/${TINYCORE_ARCH}/tcz/${1}
		return
	fi

	for file in `cat ${1}.tree`; do
		download_file ${URL}/${TINYCORE_SERIES}/${TINYCORE_ARCH}/tcz/${file}

		# Check if the file ends with "v8.tcz"
		if echo "${file}" | grep -q "v8.tcz$"; then
			# Replace "v8.tcz" with "v8-16k.tcz" and download the additional file
			additional_file=$(echo "${file}" | sed 's/v8\.tcz$/v8-16k.tcz/')
			download_file ${URL}/${TINYCORE_SERIES}/${TINYCORE_ARCH}/tcz/${additional_file}
		fi
	done
}

download_file ${URL}/${TINYCORE_SERIES}/${TINYCORE_ARCH}/release/RPi/${TINYCORE_IMAGE}.img.gz

for package in $PACKAGES; do
	download_tcz $package
done

cd /pianoberry/pianoberry

gunzip -k /build/src/${TINYCORE_IMAGE}.img.gz

dd bs=512 seek=471039 of=pianoberry.img < /dev/null
parted --script pianoberry.img \
	mklabel msdos \
	mkpart primary fat32 8192s 243711s \
	mkpart primary ext4 243712s 100%

TARGET_LOOP=$(losetup --find --show --partscan pianoberry.img)
if [ -z "$TARGET_LOOP" ]; then
	echo "Failed to create loop device for pianoberry.img"
	exit 1
fi

mkdir -p p1 p2

mkfs.vfat -F 32 -n pianoberry ${TARGET_LOOP}p1
mkfs.ext4 -L data ${TARGET_LOOP}p2

mount ${TARGET_LOOP}p1 p1
mount ${TARGET_LOOP}p2 p2

sync

SOURCE_LOOP=$(losetup --find --show --partscan ${TINYCORE_IMAGE}.img)
if [ -z "$SOURCE_LOOP" ]; then
	echo "Failed to create loop device for ${TINYCORE_IMAGE}.img"
	umount p1 p2 2>/dev/null
	losetup -d ${TARGET_LOOP} 2>/dev/null
	exit 1
fi

mkdir -p source_p1 source_p2

mount ${SOURCE_LOOP}p1 source_p1
mount ${SOURCE_LOOP}p2 source_p2

rsync -a source_p1/ p1/
rsync -a source_p2/ p2/

sync

echo "Source image info:"
fdisk -l ${TINYCORE_IMAGE}.img
df -h source_p1
df -h source_p2

echo "Target image info:"
fdisk -l pianoberry.img
df -h p1
df -h p2

# Set hostname
echo -n " pianoberry" > p1/cmdline.txt

cd /build/src

install_tcz() {
	# Some tczs don't have a .tree file
	if [ ! -f "${1}.tree" ]; then
		echo "Installing ${1}"
		cp ${1}* /pianoberry/pianoberry/p2/tce/optional
		return
	fi

	for file in `cat ${1}.tree`; do
		# Don't copy if file exists
		if [ -f "/pianoberry/pianoberry/p2/tce/optional/${file}" ]; then
			continue
		fi

		echo "Installing ${file}"
		cp ${file}* /pianoberry/pianoberry/p2/tce/optional

		if echo "${file}" | grep -q "v8.tcz$"; then
			additional_file=$(echo "${file}" | sed 's/v8\.tcz$/v8-16k.tcz/')
			echo "Installing ${additional_file}"
			cp ${additional_file}* /pianoberry/pianoberry/p2/tce/optional
		fi
	done
}

# Install the required extensions
for package in $PACKAGES; do
	install_tcz $package
done

# Enable the installed extensions
for package in $PACKAGES; do
	echo $package >> /pianoberry/pianoberry/p2/tce/onboot.lst
done

ALSA_MODULE=$(ls /pianoberry/pianoberry/p2/tce/optional/alsa-modules-*-piCore-v8-16k.tcz 2>/dev/null | sed 's|.*/||' | head -n 1)
if [ -n "$ALSA_MODULE" ]; then
	echo "$ALSA_MODULE" >> /pianoberry/pianoberry/p2/tce/onboot.lst
fi

# Disable internal sound card
sed -i 's/dtparam=audio=on/#dtparam=audio=on/g' /pianoberry/pianoberry/p1/config.txt

# Unpack the rootfs
mkdir -p /pianoberry/pianoberry/tempdir
cd /pianoberry/pianoberry/tempdir
zcat ../p1/rootfs-piCore64-16.0.gz | cpio -i

# Add Pianoteq configs
mkdir -p root/.config/Modartt
mkdir -p root/.local/share/Modartt/Pianoteq/MidiMappings

install -m 644 ../Pianoteq.prefs root/.config/Modartt/Pianoteq84.prefs
install -m 644 ../Pianoteq.prefs root/.config/Modartt/Pianoteq90.prefs
install -m 644 ../midi-map.ptm root/.local/share/Modartt/Pianoteq/MidiMappings/

# Add Pianoteq binary
install -m 777 "../Pianoteq "[89] usr/bin/Pianoteq

# Add Pianoteq startup script
install -m 777 ../startup.sh usr/bin/

mkdir -p /pianoberry/pianoberry/mydata
cd /pianoberry/pianoberry/mydata
tar -xpvzf ../mydata.tgz

# Start Pianoteq on boot
echo "/usr/bin/startup.sh" >> opt/bootlocal.sh

tar -cpvzf ../mydata.tgz .

cd /pianoberry/pianoberry

cp mydata.tgz p2/tce/

# Load pianoberry rootfs instead of the original one
sed -i 's/rootfs-piCore64-16\.0/rootfs-pianoberry/g' p1/config.txt

# Add Pianoberry default configs to pi/config.txt
cat <<EOF >> p1/config.txt

[PIANOBERRY]
pianoteq_serial=
pianoteq_initial_preset=U4 Felt II
EOF

echo "Creating the image. This may take a while..."

# Repack the rootfs
cd tempdir
find . | cpio -o -H newc | gzip > ../rootfs-pianoberry.gz
cd /pianoberry/pianoberry
advdef -z4 rootfs-pianoberry.gz
rm -f p1/rootfs-piCore64-16.0.gz
cp rootfs-pianoberry.gz p1/

sync

echo "Pianoberry image info:"
fdisk -l pianoberry.img
df -h p1
df -h p2

umount p1 p2 source_p1 source_p2
losetup -d ${SOURCE_LOOP}
losetup -d ${TARGET_LOOP}

# Copy the image to the host
cp pianoberry.img /build/pianoberry.img
